spring.application.name=Records
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=player_stats}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.default_schema=player_stats
