spring.application.name=Records
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=player_stats
spring.datasource.username=postgres
spring.datasource.password=vinay
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.default_schema=player_stats
